/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.univalle.businessmanagment.views;

/**
 *
 * @author Alejandra
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundDashboard = new javax.swing.JPanel();
        listadoOpciones = new javax.swing.JTabbedPane();
        panelUsuario = new javax.swing.JPanel();
        datosUsuarios = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txt6 = new javax.swing.JLabel();
        TipeID = new javax.swing.JComboBox<>();
        nombreUsTxt = new javax.swing.JTextField();
        apellidoUsTxt = new javax.swing.JTextField();
        identificacionUsTxt = new javax.swing.JTextField();
        telefonoUsTxt = new javax.swing.JTextField();
        añadirUsBtn = new javax.swing.JButton();
        registroUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        idUsTxt = new javax.swing.JTextField();
        buscarUsBtn = new javax.swing.JButton();
        editarUsBtn = new javax.swing.JButton();
        borrarUsBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnUsVolver = new javax.swing.JButton();
        panelCliente = new javax.swing.JPanel();
        datosClientes = new javax.swing.JPanel();
        txt5 = new javax.swing.JLabel();
        txt7 = new javax.swing.JLabel();
        txt8 = new javax.swing.JLabel();
        txt9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreCliTxt = new javax.swing.JTextField();
        apellidoCliTxt = new javax.swing.JTextField();
        identificacionCliTxt = new javax.swing.JTextField();
        telefonoCliTxt = new javax.swing.JTextField();
        correoCliTXt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        añadirCliBtn = new javax.swing.JButton();
        registroClientes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        idCliTxt = new javax.swing.JTextField();
        buscarCliBtn = new javax.swing.JButton();
        editarCliBtn = new javax.swing.JButton();
        borrarCliBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnUsVolver1 = new javax.swing.JButton();
        panelProveedores = new javax.swing.JPanel();
        datosProveedores = new javax.swing.JPanel();
        nombreProveedor = new javax.swing.JLabel();
        idProveedor = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        identificacionTxt = new javax.swing.JTextField();
        añadirProBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        registroProveedores = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        buscarProBtn = new javax.swing.JButton();
        identificacion = new javax.swing.JLabel();
        identificacionProTxt = new javax.swing.JTextField();
        editarProBtn = new javax.swing.JButton();
        borrarProBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundDashboard.setBackground(new java.awt.Color(255, 255, 255));
        backgroundDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panelUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datosUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        datosUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Usuario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txt1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt1.setForeground(new java.awt.Color(0, 0, 0));
        txt1.setText("Nombre:");

        txt2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt2.setForeground(new java.awt.Color(0, 0, 0));
        txt2.setText("Apellido:");

        txt3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt3.setForeground(new java.awt.Color(0, 0, 0));
        txt3.setText("Tipo ID:");
        txt3.setToolTipText("");

        txt4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt4.setForeground(new java.awt.Color(0, 0, 0));
        txt4.setText("Número ID:");
        txt4.setToolTipText("");

        txt6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt6.setForeground(new java.awt.Color(0, 0, 0));
        txt6.setText("Teléfono:");

        TipeID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.C", "C.E", "NIT", "PEP" }));

        nombreUsTxt.setText("jTextField1");

        apellidoUsTxt.setText("jTextField1");

        identificacionUsTxt.setText("jTextField1");

        telefonoUsTxt.setText("jTextField1");

        añadirUsBtn.setBackground(new java.awt.Color(255, 255, 255));
        añadirUsBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        añadirUsBtn.setForeground(new java.awt.Color(0, 0, 0));
        añadirUsBtn.setText("Añadir");
        añadirUsBtn.setToolTipText("");
        añadirUsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        añadirUsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirUsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosUsuariosLayout = new javax.swing.GroupLayout(datosUsuarios);
        datosUsuarios.setLayout(datosUsuariosLayout);
        datosUsuariosLayout.setHorizontalGroup(
            datosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(datosUsuariosLayout.createSequentialGroup()
                        .addComponent(txt6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoUsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(datosUsuariosLayout.createSequentialGroup()
                        .addComponent(nombreUsTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidoUsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipeID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identificacionUsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(añadirUsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );
        datosUsuariosLayout.setVerticalGroup(
            datosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosUsuariosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(datosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1)
                    .addComponent(nombreUsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2)
                    .addComponent(apellidoUsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3)
                    .addComponent(TipeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt4)
                    .addComponent(identificacionUsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoUsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(añadirUsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelUsuario.add(datosUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 56, 690, -1));

        registroUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        registroUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registro de Usuarios", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        tablaUsuarios.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Tipo ID", "Número ID", "Teléfono"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Identificación:");

        idUsTxt.setText("jTextField1");
        idUsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUsTxtActionPerformed(evt);
            }
        });

        buscarUsBtn.setBackground(new java.awt.Color(255, 255, 255));
        buscarUsBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buscarUsBtn.setForeground(new java.awt.Color(0, 0, 0));
        buscarUsBtn.setText("Buscar");
        buscarUsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarUsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsBtnActionPerformed(evt);
            }
        });

        editarUsBtn.setBackground(new java.awt.Color(255, 255, 255));
        editarUsBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editarUsBtn.setForeground(new java.awt.Color(0, 0, 0));
        editarUsBtn.setText("Editar");
        editarUsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editarUsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsBtnActionPerformed(evt);
            }
        });

        borrarUsBtn.setBackground(new java.awt.Color(255, 255, 255));
        borrarUsBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        borrarUsBtn.setForeground(new java.awt.Color(0, 0, 0));
        borrarUsBtn.setText("Borrar");
        borrarUsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout registroUsuariosLayout = new javax.swing.GroupLayout(registroUsuarios);
        registroUsuarios.setLayout(registroUsuariosLayout);
        registroUsuariosLayout.setHorizontalGroup(
            registroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroUsuariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idUsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarUsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(registroUsuariosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(registroUsuariosLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(editarUsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borrarUsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
        );
        registroUsuariosLayout.setVerticalGroup(
            registroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroUsuariosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(registroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarUsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(idUsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(registroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrarUsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarUsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelUsuario.add(registroUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jPanel2.setBackground(new java.awt.Color(98, 82, 85));

        btnUsuario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUsuario.setText("Usuarios");
        btnUsuario.setBorder(null);
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseClicked(evt);
            }
        });
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnProveedores.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setBorder(null);
        btnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseClicked(evt);
            }
        });
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        btnClientes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        panelUsuario.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 260, 780));

        btnUsVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnUsVolver.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        btnUsVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnUsVolver.setText("Volver");
        btnUsVolver.setBorder(null);
        btnUsVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsVolverMouseClicked(evt);
            }
        });
        btnUsVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsVolverActionPerformed(evt);
            }
        });
        panelUsuario.add(btnUsVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 90, 20));

        listadoOpciones.addTab("Usuario", panelUsuario);

        panelCliente.setBackground(new java.awt.Color(255, 255, 255));
        panelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datosClientes.setBackground(new java.awt.Color(255, 255, 255));
        datosClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txt5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt5.setForeground(new java.awt.Color(0, 0, 0));
        txt5.setText("Nombre:");

        txt7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt7.setForeground(new java.awt.Color(0, 0, 0));
        txt7.setText("Apellido:");

        txt8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt8.setForeground(new java.awt.Color(0, 0, 0));
        txt8.setText("Identificación");
        txt8.setToolTipText("");

        txt9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt9.setForeground(new java.awt.Color(0, 0, 0));
        txt9.setText("Teléfono:");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("E-mail:");

        nombreCliTxt.setText("jTextField1");

        apellidoCliTxt.setText("jTextField1");

        identificacionCliTxt.setText("jTextField1");

        telefonoCliTxt.setText("jTextField1");

        correoCliTXt.setText("jTextField2");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        añadirCliBtn.setBackground(new java.awt.Color(255, 255, 255));
        añadirCliBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        añadirCliBtn.setForeground(new java.awt.Color(0, 0, 0));
        añadirCliBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/añadir.png"))); // NOI18N
        añadirCliBtn.setText("Añadir");
        añadirCliBtn.setToolTipText("");
        añadirCliBtn.setBorder(null);
        añadirCliBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout datosClientesLayout = new javax.swing.GroupLayout(datosClientes);
        datosClientes.setLayout(datosClientesLayout);
        datosClientesLayout.setHorizontalGroup(
            datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosClientesLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosClientesLayout.createSequentialGroup()
                        .addGroup(datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreCliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt5)
                            .addComponent(txt7)
                            .addComponent(apellidoCliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(datosClientesLayout.createSequentialGroup()
                        .addComponent(identificacionCliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosClientesLayout.createSequentialGroup()
                        .addComponent(añadirCliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosClientesLayout.createSequentialGroup()
                            .addGroup(datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(correoCliTXt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(118, 118, 118))
                        .addGroup(datosClientesLayout.createSequentialGroup()
                            .addGroup(datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt9)
                                .addComponent(telefonoCliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))))
        );
        datosClientesLayout.setVerticalGroup(
            datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosClientesLayout.createSequentialGroup()
                        .addComponent(nombreCliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt7))
                    .addGroup(datosClientesLayout.createSequentialGroup()
                        .addComponent(correoCliTXt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosClientesLayout.createSequentialGroup()
                        .addComponent(apellidoCliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(añadirCliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(identificacionCliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(telefonoCliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(datosClientesLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelCliente.add(datosClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        registroClientes.setBackground(new java.awt.Color(255, 255, 255));
        registroClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registro de Clientes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Identificación", "E-mail", "Teléfono"
            }
        ));
        jScrollPane2.setViewportView(tablaClientes);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Identificación: ");

        idCliTxt.setText("jTextField1");
        idCliTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCliTxtActionPerformed(evt);
            }
        });

        buscarCliBtn.setBackground(new java.awt.Color(255, 255, 255));
        buscarCliBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buscarCliBtn.setForeground(new java.awt.Color(0, 0, 0));
        buscarCliBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        buscarCliBtn.setText("Buscar");
        buscarCliBtn.setBorder(null);
        buscarCliBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarCliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCliBtnActionPerformed(evt);
            }
        });

        editarCliBtn.setBackground(new java.awt.Color(255, 255, 255));
        editarCliBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editarCliBtn.setForeground(new java.awt.Color(0, 0, 0));
        editarCliBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        editarCliBtn.setText("Editar");
        editarCliBtn.setBorder(null);
        editarCliBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarCliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCliBtnActionPerformed(evt);
            }
        });

        borrarCliBtn.setBackground(new java.awt.Color(255, 255, 255));
        borrarCliBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        borrarCliBtn.setForeground(new java.awt.Color(0, 0, 0));
        borrarCliBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borrar.png"))); // NOI18N
        borrarCliBtn.setText("Borrar");
        borrarCliBtn.setBorder(null);
        borrarCliBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout registroClientesLayout = new javax.swing.GroupLayout(registroClientes);
        registroClientes.setLayout(registroClientesLayout);
        registroClientesLayout.setHorizontalGroup(
            registroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroClientesLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idCliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarCliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(registroClientesLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(editarCliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(borrarCliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        registroClientesLayout.setVerticalGroup(
            registroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroClientesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(registroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idCliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarCliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarCliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        panelCliente.add(registroClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 380));

        jPanel1.setBackground(new java.awt.Color(98, 82, 85));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        panelCliente.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 260, 780));

        btnUsVolver1.setBackground(new java.awt.Color(204, 204, 204));
        btnUsVolver1.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        btnUsVolver1.setForeground(new java.awt.Color(0, 0, 0));
        btnUsVolver1.setText("Volver");
        btnUsVolver1.setBorder(null);
        btnUsVolver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsVolver1MouseClicked(evt);
            }
        });
        btnUsVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsVolver1ActionPerformed(evt);
            }
        });
        panelCliente.add(btnUsVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 90, 20));

        listadoOpciones.addTab("Cliente", panelCliente);

        panelProveedores.setBackground(new java.awt.Color(255, 255, 255));

        datosProveedores.setBackground(new java.awt.Color(255, 255, 255));
        datosProveedores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Proveedores\n", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        nombreProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombreProveedor.setForeground(new java.awt.Color(0, 0, 0));
        nombreProveedor.setText("Nombre:");

        idProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        idProveedor.setForeground(new java.awt.Color(0, 0, 0));
        idProveedor.setText("Identificación:");
        idProveedor.setToolTipText("");

        nombreTxt.setText("jTextField1");

        identificacionTxt.setText("jTextField1");
        identificacionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionTxtActionPerformed(evt);
            }
        });

        añadirProBtn.setBackground(new java.awt.Color(255, 255, 255));
        añadirProBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        añadirProBtn.setForeground(new java.awt.Color(0, 0, 0));
        añadirProBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        añadirProBtn.setText("Añadir");
        añadirProBtn.setToolTipText("");
        añadirProBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout datosProveedoresLayout = new javax.swing.GroupLayout(datosProveedores);
        datosProveedores.setLayout(datosProveedoresLayout);
        datosProveedoresLayout.setHorizontalGroup(
            datosProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosProveedoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(añadirProBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(datosProveedoresLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(datosProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idProveedor)
                    .addComponent(nombreProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identificacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        datosProveedoresLayout.setVerticalGroup(
            datosProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosProveedoresLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(datosProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreProveedor))
                .addGap(18, 18, 18)
                .addGroup(datosProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(añadirProBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(98, 82, 85));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        registroProveedores.setBackground(new java.awt.Color(255, 255, 255));
        registroProveedores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registro de Proveedores\n", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Identificación"
            }
        ));
        jScrollPane3.setViewportView(tablaProveedores);

        buscarProBtn.setBackground(new java.awt.Color(255, 255, 255));
        buscarProBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buscarProBtn.setForeground(new java.awt.Color(0, 0, 0));
        buscarProBtn.setText("Buscar");
        buscarProBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarProBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProBtnActionPerformed(evt);
            }
        });

        identificacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        identificacion.setForeground(new java.awt.Color(0, 0, 0));
        identificacion.setText("Identificación:");

        identificacionProTxt.setText("jTextField1");
        identificacionProTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionProTxtActionPerformed(evt);
            }
        });

        editarProBtn.setBackground(new java.awt.Color(255, 255, 255));
        editarProBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editarProBtn.setForeground(new java.awt.Color(0, 0, 0));
        editarProBtn.setText("Editar");
        editarProBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editarProBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProBtnActionPerformed(evt);
            }
        });

        borrarProBtn.setBackground(new java.awt.Color(255, 255, 255));
        borrarProBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        borrarProBtn.setForeground(new java.awt.Color(0, 0, 0));
        borrarProBtn.setText("Borrar");
        borrarProBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout registroProveedoresLayout = new javax.swing.GroupLayout(registroProveedores);
        registroProveedores.setLayout(registroProveedoresLayout);
        registroProveedoresLayout.setHorizontalGroup(
            registroProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroProveedoresLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(identificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identificacionProTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarProBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(registroProveedoresLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(editarProBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(borrarProBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        registroProveedoresLayout.setVerticalGroup(
            registroProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroProveedoresLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(registroProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificacion)
                    .addComponent(identificacionProTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarProBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(registroProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarProBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarProBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout panelProveedoresLayout = new javax.swing.GroupLayout(panelProveedores);
        panelProveedores.setLayout(panelProveedoresLayout);
        panelProveedoresLayout.setHorizontalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addGroup(panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProveedoresLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(registroProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProveedoresLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datosProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelProveedoresLayout.setVerticalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProveedoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(datosProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(registroProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listadoOpciones.addTab("Proveedores", panelProveedores);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1057, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        listadoOpciones.addTab("Productos", jPanel4);

        backgroundDashboard.add(listadoOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirUsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirUsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadirUsBtnActionPerformed

    private void buscarUsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarUsBtnActionPerformed

    private void idUsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUsTxtActionPerformed

    private void editarUsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarUsBtnActionPerformed

    private void buscarCliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCliBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarCliBtnActionPerformed

    private void idCliTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCliTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCliTxtActionPerformed

    private void editarCliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCliBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarCliBtnActionPerformed

    private void identificacionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionTxtActionPerformed

    private void buscarProBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarProBtnActionPerformed

    private void identificacionProTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionProTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionProTxtActionPerformed

    private void editarProBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarProBtnActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseClicked
        listadoOpciones.setSelectedIndex(0);
    }//GEN-LAST:event_btnUsuarioMouseClicked

    private void btnProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseClicked
        listadoOpciones.setSelectedIndex(2);
    }//GEN-LAST:event_btnProveedoresMouseClicked

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        listadoOpciones.setSelectedIndex(1);
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnUsVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsVolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsVolverMouseClicked

    private void btnUsVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsVolverActionPerformed

    private void btnUsVolver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsVolver1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsVolver1MouseClicked

    private void btnUsVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsVolver1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsVolver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TipeID;
    private javax.swing.JTextField apellidoCliTxt;
    private javax.swing.JTextField apellidoUsTxt;
    private javax.swing.JButton añadirCliBtn;
    private javax.swing.JButton añadirProBtn;
    private javax.swing.JButton añadirUsBtn;
    private javax.swing.JPanel backgroundDashboard;
    private javax.swing.JButton borrarCliBtn;
    private javax.swing.JButton borrarProBtn;
    private javax.swing.JButton borrarUsBtn;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnUsVolver;
    private javax.swing.JButton btnUsVolver1;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton buscarCliBtn;
    private javax.swing.JButton buscarProBtn;
    private javax.swing.JButton buscarUsBtn;
    private javax.swing.JTextField correoCliTXt;
    private javax.swing.JPanel datosClientes;
    private javax.swing.JPanel datosProveedores;
    private javax.swing.JPanel datosUsuarios;
    private javax.swing.JButton editarCliBtn;
    private javax.swing.JButton editarProBtn;
    private javax.swing.JButton editarUsBtn;
    private javax.swing.JTextField idCliTxt;
    private javax.swing.JLabel idProveedor;
    private javax.swing.JTextField idUsTxt;
    private javax.swing.JLabel identificacion;
    private javax.swing.JTextField identificacionCliTxt;
    private javax.swing.JTextField identificacionProTxt;
    private javax.swing.JTextField identificacionTxt;
    private javax.swing.JTextField identificacionUsTxt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane listadoOpciones;
    private javax.swing.JTextField nombreCliTxt;
    private javax.swing.JLabel nombreProveedor;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField nombreUsTxt;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JPanel registroClientes;
    private javax.swing.JPanel registroProveedores;
    private javax.swing.JPanel registroUsuarios;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField telefonoCliTxt;
    private javax.swing.JTextField telefonoUsTxt;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel txt7;
    private javax.swing.JLabel txt8;
    private javax.swing.JLabel txt9;
    // End of variables declaration//GEN-END:variables
}
